Weaponkit:
  Prefix: "&7[&5Weaponkit&7]"

  Permissions:
    PermissionGuiUse: "weaponkit.gui.use"
    PermissionCommandUse: "weaponkit.command.use"
    NetherWartGive: "weaponkit.netherstar.give"
    ItemGive: "weaponkit.item.give"
    CooldownReset: "cooldown.reset.use"
    ActivateCraft: "activate.craft.use"

  ConsoleCommand:
    NotAPlayerCommand: "&cThis Command can only be use by the &aConsole."

  WeaponkitGui:
    Name: "&7[&5Weaponkit&7]"
    # Size is how many slots the gui should have.
    Size: 27 # Note remember to have as many slots as you have items, you can have more if you want.
    GetSlotNrOnItemClick: false # How to enable: set it to: true

  CoolDown:
    WaitMessage: "&7Please wait until the &acooldown &7has run out. Time left:&5"
    ResetMessage: "&7Your &acooldown &7has been &3reset"

  Messages:
    PermissionMessage: "&cYou do not have permission to use this command."
    ActivateCraftOnMessage: "&7Can now use custom crafts."
    ActivateCraftOffMessage: "Can no longer use custom crafts."
    ActivateCraftIsOffMessage: "&cYour not allowed to use custom crafts."
    HelpMessage:
      - "&7----------------- &aHelp &7---------------"
      - "&5/WeaponKit help &7- To see how to use this command"
      - "&5/WeaponKit &7 to open a Gui and choose your item"
      - "&5/WeaponKit List &7- To see what type of items are available"
      - "&5/WeaponKit <Player> Star &7- To receive a Nether star, right click it an receive a kit of wither armor and sword"
      - "&5/WeaponKit <Player> <ItemType> <EffectType> &7- To give a player a item"
      - "&5/Weaponkit <Player <Wither> <Item> &7- To give the a player a wither item"
      - "&5/ActivateCraft <Player> <On/Off> &7- To allow/deny the player to use CustomCrafts"
      - "&7-------------------------------------"

  Items:
    ListItemsCommand:
      - "&7----------------- &aAvailable Items &7---------------"
      - "&5Sword: &7- Poison, Blindness, Nausea and Wither"
      - "&5Axe: &7- Poison, Blindness, Nausea and Wither"
      - "&5Bow: &7- Multi and Wither"
      - "&5Wither: &7- Kit, Tear, Helmet, ChestPlate, Leggins and Boots"
      - "&7----------------------------------------------"

# Important note!! Only one item in a slot
    WitherTear:
      Enchantments: true # How to disable: set it to: false
      Soulbound: true # How to disable: set it to: false
      Name: '&5Wither Tear'
      DisplayItemInGui: true # How to disable: set it to: false
      SlotNumber: 18

    Armor:
      WitherHelmet:
        Enchantments: true # How to disable: set it to: false
        Soulbound: true # How to disable: set it to: false
        Name: '&5Wither Helmet'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 23

      WitherChestPlate:
        Enchantments: true # How to disable: set it to: false
        Soulbound: true # How to disable: set it to: false
        Name: '&5Wither ChestPlate'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 24

      WitherLeggings:
        Enchantments: true # How to disable: set it to: false
        Soulbound: true # How to disable: set it to: false
        Name: '&5Wither Leggings'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 25

      WitherBoots:
        Enchantments: true # How to disable: set it to: false
        Soulbound: true # How to disable: set it to: false
        Name: '&5Wither Boots'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 26

    Axe:
      PoisonAxeConfig:
        Soulbound: true
        Enchantments: true
        Name: '&5PoisonAxe'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 9

      NauseaAxeConfig:
        Soulbound: true
        Enchantments: true
        Name: '&3NauseaAxe'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 10

      BlindnessAxeConfig:
        Soulbound: true
        Enchantments: true
        Name: '&6BlindnessAxe'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 11

      WitherAxeConfig:
        Soulbound: true
        Enchantments: true
        Name: '&5WitherAxe'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 12

    Sword:
      PoisonSwordConfig:
        Soulbound: true
        Enchantments: true
        Name: '&5PoisonSword'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 0

      NauseaSwordConfig:
        Soulbound: true
        Enchantments: true
        Name: '&3NauseaSword'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 1

      BlindnessSwordConfig:
        Soulbound: true
        Enchantments: true
        Name: '&6BlindnessSword'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 2

      WitherSwordConfig:
        Soulbound: true
        Enchantments: true
        Name: '&5WitherSword'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 3
    Bow:
      Multi:
        Soulbound: true
        Enchantments: true
        Name: '&6Multi Bow'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 7
      Wither:
        Soulbound: true
        Enchantments: true
        Name: '&5WitherBow'
        DisplayItemInGui: true # How to disable: set it to: false
        SlotNumber: 8